// Code generated by "stringer -type=AppMessageType -linecomment=true"; DO NOT EDIT.

package openwechat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AppMsgTypeText-1]
	_ = x[AppMsgTypeImg-2]
	_ = x[AppMsgTypeAudio-3]
	_ = x[AppMsgTypeVideo-4]
	_ = x[AppMsgTypeUrl-5]
	_ = x[AppMsgTypeAttach-6]
	_ = x[AppMsgTypeOpen-7]
	_ = x[AppMsgTypeEmoji-8]
	_ = x[AppMsgTypeVoiceRemind-9]
	_ = x[AppMsgTypeScanGood-10]
	_ = x[AppMsgTypeGood-13]
	_ = x[AppMsgTypeEmotion-15]
	_ = x[AppMsgTypeCardTicket-16]
	_ = x[AppMsgTypeRealtimeShareLocation-17]
	_ = x[AppMsgTypeTransfers-2000]
	_ = x[AppMsgTypeRedEnvelopes-2001]
	_ = x[AppMsgTypeReaderType-100001]
}

const (
	_AppMessageType_name_0 = "文本消息图片消息语音消息视频消息文章消息附件消息Open表情消息VoiceRemindScanGood"
	_AppMessageType_name_1 = "Good"
	_AppMessageType_name_2 = "Emotion名片消息地理位置消息"
	_AppMessageType_name_3 = "转账消息红包消息"
	_AppMessageType_name_4 = "自定义的消息"
)

var (
	_AppMessageType_index_0 = [...]uint8{0, 12, 24, 36, 48, 60, 72, 76, 88, 99, 107}
	_AppMessageType_index_2 = [...]uint8{0, 7, 19, 37}
	_AppMessageType_index_3 = [...]uint8{0, 12, 24}
)

func (i AppMessageType) String() string {
	switch {
	case 1 <= i && i <= 10:
		i -= 1
		return _AppMessageType_name_0[_AppMessageType_index_0[i]:_AppMessageType_index_0[i+1]]
	case i == 13:
		return _AppMessageType_name_1
	case 15 <= i && i <= 17:
		i -= 15
		return _AppMessageType_name_2[_AppMessageType_index_2[i]:_AppMessageType_index_2[i+1]]
	case 2000 <= i && i <= 2001:
		i -= 2000
		return _AppMessageType_name_3[_AppMessageType_index_3[i]:_AppMessageType_index_3[i+1]]
	case i == 100001:
		return _AppMessageType_name_4
	default:
		return "AppMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
